// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/RmqMessage.proto

package com.uangel.rmq.message;

public interface HbReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.uangel.HbReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 svc_status = 1;</code>
   * @return The svcStatus.
   */
  int getSvcStatus();
}
