// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/RmqMessage.proto

package com.uangel.rmq.message;

public interface HeartbeatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.uangel.HeartbeatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cpu_usage = 1;</code>
   * @return The cpuUsage.
   */
  int getCpuUsage();

  /**
   * <code>int32 memory_usage = 2;</code>
   * @return The memoryUsage.
   */
  int getMemoryUsage();

  /**
   * <code>int32 session_count = 3;</code>
   * @return The sessionCount.
   */
  int getSessionCount();
}
