// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/RmqMessage.proto

package com.uangel.rmq.message;

public final class RmqMsg {
  private RmqMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uangel_RmqHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_uangel_RmqHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uangel_RmqMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_uangel_RmqMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uangel_HeartbeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_uangel_HeartbeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uangel_HbReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_uangel_HbReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/protoc/RmqMessage.p" +
      "roto\022\ncom.uangel\"x\n\tRmqHeader\022\014\n\004type\030\001 " +
      "\001(\t\022\025\n\rtransactionId\030\002 \001(\t\022\017\n\007msgFrom\030\003 " +
      "\001(\t\022\021\n\ttimestamp\030\004 \001(\t\022\022\n\nreasonCode\030\005 \001" +
      "(\005\022\016\n\006reason\030\006 \001(\t\"A\n\nRmqMessage\022%\n\006head" +
      "er\030\001 \001(\0132\025.com.uangel.RmqHeader\022\014\n\004body\030" +
      "\002 \001(\014\"N\n\014HeartbeatReq\022\021\n\tcpu_usage\030\001 \001(\005" +
      "\022\024\n\014memory_usage\030\002 \001(\005\022\025\n\rsession_count\030" +
      "\003 \001(\005\"\033\n\005HbReq\022\022\n\nsvc_status\030\001 \001(\005B\"\n\026co" +
      "m.uangel.rmq.messageB\006RmqMsgP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_uangel_RmqHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_uangel_RmqHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_uangel_RmqHeader_descriptor,
        new java.lang.String[] { "Type", "TransactionId", "MsgFrom", "Timestamp", "ReasonCode", "Reason", });
    internal_static_com_uangel_RmqMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_uangel_RmqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_uangel_RmqMessage_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_com_uangel_HeartbeatReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_uangel_HeartbeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_uangel_HeartbeatReq_descriptor,
        new java.lang.String[] { "CpuUsage", "MemoryUsage", "SessionCount", });
    internal_static_com_uangel_HbReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_uangel_HbReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_uangel_HbReq_descriptor,
        new java.lang.String[] { "SvcStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
