// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/RmqMessage.proto

package com.uangel.rmq.message;

public interface RmqMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.uangel.RmqMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.uangel.RmqHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.com.uangel.RmqHeader header = 1;</code>
   * @return The header.
   */
  com.uangel.rmq.message.RmqHeader getHeader();
  /**
   * <code>.com.uangel.RmqHeader header = 1;</code>
   */
  com.uangel.rmq.message.RmqHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
